### ISSUE TITLE
functorch 1.13 release tracker

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#1038]
Here are the remaining items we should do before the PyTorch 1.13 release. Note that PyTorch 1.13 has cut a release branch, so if we are going to find bugs, we should find and fix them soon. The absolute deadline is 10/21.

- [ ] AOTAutograd tutorial is broken. It doesn't run and appears to give silently incorrect results. @Chillee 
- [ ] TorchBench microbenchmark regression suite, test new release for regressions @zou3519 
- [ ] Release functorch 1.13 pip binary (this is a dummy binary) @zou3519 
- [ ] Test functorch over torchbench models @kshitij12345 Tests do not need to go into the release; we should try to fix any hi-pri bugs we find as a result of this.
- [ ] https://github.com/pytorch/functorch/issues/1029 . Tests do not need to go into the release; we should try to fix any hi-pri bugs we find as a result of this.
- [ ] PyTorch release notes and release blurb
