### ISSUE TITLE
functorch preview branch checklist

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#224]
Add and audit docstrings for APIs
- [x] vmap @zou3519 
- [x] grad (#231), grad_and_value @samdow 
- [x] vjp @samdow 
- [x] jacrev @samdow 
- [x] make_fx @zou3519 (resolution: I don't think I'm going to document this)
- [x] vjpfull (Confirm if this should be exposed. I don't think it should be) @zou3519 
- [x] make_functional, make_functional_with_buffers, FunctionalModule @zou3519 
- [x] combine_state_for_ensemble @zou3519 
- [x] Figure out if {make_functional, make_functional_with_buffers, FunctionalModule, combine_state_for_ensemble} need their own namespace. @zou3519 
- [x] Should we expose all of {wrap_key, PythonTensor, pythonkey_trace, make_fx}? Hypothesis: we only need to expose make_fx  @zou3519 
- [x] all compile things go into functorch.compile @zou3519 
- [x] Excise functional_init* @zou3519 

Do we need a docs website?
- [x] Answer the question
- [x] Make the site @zou3519

Installation instructions
- [x] Add installation instructions for PyTorch 1.10 to README / website. Set up colab notebook with PyTorch 1.10 installation. @zou3519

Misc
- [x] delete the deepcopy in make_functional @zou3519 
- [x] delete make_functional_deprecated_v1, make_functional_with_buffers_deprecated_v1 (it's been long enough)
- [x] Perform cherry-picks of all of the above into the 1.10 branch @zou3519 
- [x] Push docs website (functorch.github.io) and link from readme @zou3519 
- [ ] Marketing (tweets) @Chillee

**Comment by zou3519** [comment]
One item left!

**Comment by zou3519** [comment]
We did the preview branch
