### ISSUE TITLE
[v0.1.0] Release Tracker

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#507]
We cut a [release branch](https://github.com/pytorch/functorch/tree/release/0.1) for the 0.1.0 release.

This issue is for coordinating and tracking cherry-picks to the release branch. Things might start getting hectic if all of us cherry-pick things to the release branch at the same time, so if you want something cherry-picked to the release branch, comment with a link to a PR that has been merged into the main branch and @zou3519 will cherry-pick, ensure the tests pass, and reach out if anything went wrong.

**Comment by samdow** [comment]
- [ ] PR #411  Because of ghstack, it's commit on main is [1986cf7](https://github.com/pytorch/functorch/commit/1986cf7bbd453ccf7e4f6dadb62d55effb566625)

**Comment by samdow** [comment]
- [ ] #412 d775bc17217c93545672a819c85f776b827ffd1f
- [ ] #510 30f742d98fd04c0714810b90f56f7e0bfdf5e7e1
- [ ] #511 30f742d98fd04c0714810b90f56f7e0bfdf5e7e1
- [ ] #521 057c3cacade334effd1210eb98382400988849d5
- [ ] #558 54c867145bee73b52fd137f717090720f888b3cb
- [ ] #523 1fa54342eab96040ad6a71bbe7348bd7d0ffeb8b

**Comment by anijain2305** [comment]
AOT Autograd Documentation stuff

- [ ] https://github.com/pytorch/functorch/pull/577
- [ ] https://github.com/pytorch/functorch/pull/580
- [ ] https://github.com/pytorch/functorch/pull/585

**Comment by zou3519** [comment]
We've released!
