### ISSUE TITLE
[v0.2.0 Release Tracker]

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#826]
We cut a [release branch](https://github.com/pytorch/functorch/tree/release/0.2) for the 0.2.0 release.

This issue is for coordinating and tracking cherry-picks to the release branch. Things might start getting hectic if all of us cherry-pick things to the release branch at the same time, so if you want something cherry-picked to the release branch, comment with a link to a PR that has been merged into the main branch and @zou3519 will cherry-pick, ensure the tests pass, and reach out if anything went wrong.

**Comment by samdow** [comment]
- [ ] https://github.com/pytorch/functorch/pull/860

**Comment by zou3519** [comment]
- [ ] https://github.com/pytorch/functorch/pull/845
- [ ] https://github.com/pytorch/functorch/pull/849
- [ ] https://github.com/pytorch/functorch/pull/862

**Comment by zou3519** [comment]
- [ ] https://github.com/pytorch/functorch/pull/874
- [ ] https://github.com/pytorch/functorch/pull/879

**Comment by anijain2305** [comment]
- [ ] https://github.com/pytorch/functorch/pull/794 (cc @Chillee)

@zou3519 Let me know if you need any help here.
