### ISSUE TITLE
v0.2.0 Release Work Items

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#827]
## P0 (needs to be done)
- [ ] {linux, mac, windows} binaries setup @zou3519 
- [ ] documentation website setup @zou3519 
- [ ] windows binaries test
- [x] cherry-pick https://github.com/pytorch/functorch/pull/849
- [x] Decision on M1 binaries ( probably not worth it, because pytorch/pytorch M1 support is problematic)

## P1 (can be pushed to next release, but is important)
- [ ] Improved alias and in-place testing (parcel 0 in https://github.com/pytorch/functorch/issues/614)
- [ ] chunk API https://github.com/pytorch/functorch/issues/680
- [ ] Complete some of the open JVP coverage items (https://github.com/pytorch/functorch/issues/658)

## P2 (wishlist)
- [ ] More batching rules (parcel 1&2 in https://github.com/pytorch/functorch/issues/614)
- [ ] vmap over autograd.grad testing
